[programs.localnet]
cryptails = "CELEWojrkyqTYFqkevnTQi6rtLwwSMTbRc5vZAy2KwPc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/apokh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
